### ISSUE TITLE
[bug] dependency `cli-color` has licensing issues

### ISSUE THREAD

**Issue by DerekNonGeneric** [openinf/util-text#56]
According to Socket, [`cli-color` has issues](https://socket.dev/npm/package/cli-color/issues/2.0.3) related to licensing. We are currently using the MIT license for the packages we publish on npm and intend to continue doing so. This is kind of a hard requirement since a lot of projects have a strict requirement of having an MIT license. It is also important that the dependencies of our dependencies are MIT licensed as well.

We may be able to swap this one out for [`colorette`](https://www.npmjs.com/package/colorette), which is MIT-licensed ([silver quality](https://socket.dev/npm/package/colorette)) and maintained by my good friend @jorgebucaran. It has no dependencies.

Refs: https://github.com/DerekNonGeneric/loader339/pull/11#discussion_r478740474

**Comment by dadolhay** [comment]
Hi @DerekNonGeneric,

I posted a PR for this ussue, but I'm having some problems with some of the tests required by your repo:
I managed to fix all but two, both of them are complaining against the autogenerated index.js file (`npm run prepare`)

I'd think that this file, being automatically generated, should be excluded from these tests, but if you'd like, I'd be more than happy to apply some changes to it

**Comment by DerekNonGeneric** [comment]
Hi @dadolhay, thanks; that would be cool by me.

If you prefer, you can also exclude the out-generated file from your changes.

**Comment by dadolhay** [comment]
@DerekNonGeneric 

I made two changes:
- I started using normal named imports (renaming them one by one to avoid naming collision)
- I completely excluded `index.js` from the PR

With this it seems all tests are passing, but please note, that the functionality of `index.js` and `index.ts` differs

**Comment by DerekNonGeneric** [comment]
Yeah, thanks! Noted; that would need to be taken care of in a separate PR. The issue for it is #115. :)
